export const RANKS = '23456789TJQKA';
export const SUITS = 'SHCD';

const ROYALFLUSH = 1;
const STRAIGHTFLUSH = 2;
const FOUROFAKIND = 3;
const FULLHOUSE = 4;
const FLUSH = 5;
const STRAIGHT = 6;
const THREEOFAKIND = 7;
const TWOPAIR = 8;
const ONEPAIR = 9;
const NOTHING = 10;

export const SCORE = {
  ROYALFLUSH,
  STRAIGHTFLUSH,
  FOUROFAKIND,
  FULLHOUSE,
  FLUSH,
  STRAIGHT,
  THREEOFAKIND,
  TWOPAIR,
  ONEPAIR,
  NOTHING,
}
